---
# GraphQL Linter Configuration
# This file allows you to suppress specific linter warnings and errors

suppressions:
  # Suppress suspicious enum value warnings for specific cases
  - file: test/testdata/graphql/suspicious-enum-value.graphql
    line: 4
    rule: suspicious_enum_value
    value: PO4_VOLUME
    reason: PO4_VOLUME is valid domain-specific enum value phosphate volume

# Example suppressions for other rule types:
# - file: "path/to/schema.graphqls"
#   line: 42
#   rule: "undefined_type"
#   value: "CustomType"
#   reason: "CustomType is defined externally in federation"
#
# - file: "path/to/schema.graphqls"
#   line: 15
#   rule: "invalid_directive"
#   value: "customDirective"
#   reason: "Custom directive allowed for this specific use case"

# Global settings
settings:
  # Whether to treat warnings as errors (default: false)
  strictMode: true

  # Whether to validate federation directives (default: true)
  validateFederation: true

  # Whether to check for missing descriptions (default: true)
  checkDescriptions: true
