// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/schubergphilis/graphql-linter/internal/app/graphql-linter/data/base/models"
	mock "github.com/stretchr/testify/mock"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/ast"
)

// NewStorer creates a new instance of Storer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storer {
	mock := &Storer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storer is an autogenerated mock type for the Storer type
type Storer struct {
	mock.Mock
}

type Storer_Expecter struct {
	mock *mock.Mock
}

func (_m *Storer) EXPECT() *Storer_Expecter {
	return &Storer_Expecter{mock: &_m.Mock}
}

// FindAndLogGraphQLSchemaFiles provides a mock function for the type Storer
func (_mock *Storer) FindAndLogGraphQLSchemaFiles() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAndLogGraphQLSchemaFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storer_FindAndLogGraphQLSchemaFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAndLogGraphQLSchemaFiles'
type Storer_FindAndLogGraphQLSchemaFiles_Call struct {
	*mock.Call
}

// FindAndLogGraphQLSchemaFiles is a helper method to define mock.On call
func (_e *Storer_Expecter) FindAndLogGraphQLSchemaFiles() *Storer_FindAndLogGraphQLSchemaFiles_Call {
	return &Storer_FindAndLogGraphQLSchemaFiles_Call{Call: _e.mock.On("FindAndLogGraphQLSchemaFiles")}
}

func (_c *Storer_FindAndLogGraphQLSchemaFiles_Call) Run(run func()) *Storer_FindAndLogGraphQLSchemaFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storer_FindAndLogGraphQLSchemaFiles_Call) Return(strings []string, err error) *Storer_FindAndLogGraphQLSchemaFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Storer_FindAndLogGraphQLSchemaFiles_Call) RunAndReturn(run func() ([]string, error)) *Storer_FindAndLogGraphQLSchemaFiles_Call {
	_c.Call.Return(run)
	return _c
}

// LintSchemaFiles provides a mock function for the type Storer
func (_mock *Storer) LintSchemaFiles(schemaFiles []string) (int, int, []models.DescriptionError) {
	ret := _mock.Called(schemaFiles)

	if len(ret) == 0 {
		panic("no return value specified for LintSchemaFiles")
	}

	var r0 int
	var r1 int
	var r2 []models.DescriptionError
	if returnFunc, ok := ret.Get(0).(func([]string) (int, int, []models.DescriptionError)); ok {
		return returnFunc(schemaFiles)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) int); ok {
		r0 = returnFunc(schemaFiles)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) int); ok {
		r1 = returnFunc(schemaFiles)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func([]string) []models.DescriptionError); ok {
		r2 = returnFunc(schemaFiles)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]models.DescriptionError)
		}
	}
	return r0, r1, r2
}

// Storer_LintSchemaFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LintSchemaFiles'
type Storer_LintSchemaFiles_Call struct {
	*mock.Call
}

// LintSchemaFiles is a helper method to define mock.On call
//   - schemaFiles []string
func (_e *Storer_Expecter) LintSchemaFiles(schemaFiles interface{}) *Storer_LintSchemaFiles_Call {
	return &Storer_LintSchemaFiles_Call{Call: _e.mock.On("LintSchemaFiles", schemaFiles)}
}

func (_c *Storer_LintSchemaFiles_Call) Run(run func(schemaFiles []string)) *Storer_LintSchemaFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Storer_LintSchemaFiles_Call) Return(n int, n1 int, descriptionErrors []models.DescriptionError) *Storer_LintSchemaFiles_Call {
	_c.Call.Return(n, n1, descriptionErrors)
	return _c
}

func (_c *Storer_LintSchemaFiles_Call) RunAndReturn(run func(schemaFiles []string) (int, int, []models.DescriptionError)) *Storer_LintSchemaFiles_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConfig provides a mock function for the type Storer
func (_mock *Storer) LoadConfig() (*models.LinterConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *models.LinterConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*models.LinterConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *models.LinterConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LinterConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storer_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type Storer_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
func (_e *Storer_Expecter) LoadConfig() *Storer_LoadConfig_Call {
	return &Storer_LoadConfig_Call{Call: _e.mock.On("LoadConfig")}
}

func (_c *Storer_LoadConfig_Call) Run(run func()) *Storer_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storer_LoadConfig_Call) Return(linterConfig *models.LinterConfig, err error) *Storer_LoadConfig_Call {
	_c.Call.Return(linterConfig, err)
	return _c
}

func (_c *Storer_LoadConfig_Call) RunAndReturn(run func() (*models.LinterConfig, error)) *Storer_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UnsortedTypeFields provides a mock function for the type Storer
func (_mock *Storer) UnsortedTypeFields(doc *ast.Document, schemaString string) []models.DescriptionError {
	ret := _mock.Called(doc, schemaString)

	if len(ret) == 0 {
		panic("no return value specified for UnsortedTypeFields")
	}

	var r0 []models.DescriptionError
	if returnFunc, ok := ret.Get(0).(func(*ast.Document, string) []models.DescriptionError); ok {
		r0 = returnFunc(doc, schemaString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DescriptionError)
		}
	}
	return r0
}

// Storer_UnsortedTypeFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsortedTypeFields'
type Storer_UnsortedTypeFields_Call struct {
	*mock.Call
}

// UnsortedTypeFields is a helper method to define mock.On call
//   - doc *ast.Document
//   - schemaString string
func (_e *Storer_Expecter) UnsortedTypeFields(doc interface{}, schemaString interface{}) *Storer_UnsortedTypeFields_Call {
	return &Storer_UnsortedTypeFields_Call{Call: _e.mock.On("UnsortedTypeFields", doc, schemaString)}
}

func (_c *Storer_UnsortedTypeFields_Call) Run(run func(doc *ast.Document, schemaString string)) *Storer_UnsortedTypeFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ast.Document
		if args[0] != nil {
			arg0 = args[0].(*ast.Document)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storer_UnsortedTypeFields_Call) Return(descriptionErrors []models.DescriptionError) *Storer_UnsortedTypeFields_Call {
	_c.Call.Return(descriptionErrors)
	return _c
}

func (_c *Storer_UnsortedTypeFields_Call) RunAndReturn(run func(doc *ast.Document, schemaString string) []models.DescriptionError) *Storer_UnsortedTypeFields_Call {
	_c.Call.Return(run)
	return _c
}
