---
name: mcvs-golang-action-taskfile-remote-url-ref-updater
"on":
  schedule:
    - cron: 42 6 * * *
permissions:
  contents: write
  pull-requests: write
jobs:
  mcvs-golang-action-taskfile-remote-url-ref-updater:
    runs-on: ubuntu-slim
    steps:
      # yamllint disable rule:line-length
      - uses: schubergphilis/mcvs-golang-action-taskfile-remote-url-ref-updater@bac758bc0d4e3ee9b174ae4c24b43717e371f248 # v0.2.0
